# Generated by Django 3.1.7 on 2021-03-12 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('password2', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Данные пациентов',
                'verbose_name_plural': 'данные пациентов',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=100)),
                ('mail_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='medsite.login')),
            ],
            options={
                'verbose_name': 'Пациенты',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['name'],
            },
        ),
    ]
