# Generated by Django 3.1.7 on 2021-03-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='электроная почта'),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=255, verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.CharField(max_length=100, verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=255, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(max_length=255, verbose_name='фамилия'),
        ),
    ]
