# Generated by Django 3.1.7 on 2021-04-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsite', '0002_auto_20210315_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password2',
            field=models.CharField(max_length=255, verbose_name='повторите пароль'),
        ),
    ]
